### ISSUE TITLE
Can someone create a TB extension dumping unread information as JSON?

### ISSUE THREAD

**Issue by gyunaev** [gyunaev/birdtray#12]
If anyone here has some free time and knowledge of Thunderbird extensions, I'd like to ask for help.

The current way I query the unread status from Thunderbird has two major disadvantages:
- "read" status frequently gets broken if you use IMAP and your network connectivity fails (Thunderbird does not change the database status to 'read' until server confirms it), and users end up using "Fix" button too often;
- It is impossible to show things like server connectivity errors, chat connection status and chat messages (to fix #1).

To address those issues I'd like to have an extension, likely based on a stripped-down FireTray. It should do the following:

1. Listen on new mail and chat notifications, and connectivity status;
2. Upon those events, create a file "mailstatus.json" in Thunderbird directory, listing:
  - each email and chat account folder with the number of unread and total messages;
  - each email and chat account with the current connectivity status for each;

I would then alter Birdtray to use this information, as this would allow much better user experience.

The advantage of this approach is that it does not depend on js-ctypes and thus will not be broken as long as XUL is supported by TB.

**Comment by DisposaBoy** [comment]
Have you thought about querying the `Inbox.msf` *databases*? I haven't tried it, but I believe it should solve some/all of the issues you currently have with using the search db (birdtray actually doesn't work for me because I don't have search enabled).

These `Inbox.msf` files are https://en.wikipedia.org/wiki/Mork_(file_format) databases and I believe they're always up-to-date and exists for each account you add to TB.

If you mark a message as un-read in TB, you should see new lines appended to the corresponding `Inbox.msf` file that contains a strings like `...(^A2=1)...` where the `A2=numNewMsgs` and `1` is the count of unread messages. 

I can have a look at it if you like, but my C++ is rusty and I probably won't have time until next week.

**Comment by gyunaev** [comment]
I indeed spent some time looking at it. In fact the first (unpublished) version of Birdtray used it. The parser however was incomplete, and the format is... to be polite... not very well designed nor documented. 

There are two problems here:

1. The msf files are NOT always up to date. It is the same issue as with sqlite database, there is a delay. Thus it does not solve the problem with delayed unread counter.
2. I have to watch and reparse several files, while they are being changed. The format has no concurrency support, and Thunderbird doesn't expect anyone to read it, thus the chance is high for it to be broken.

This is in addition to the format claimed by Thunderbird team as being deprecated, and that it does not solve the missing chat notification issues, as unread chat messages are not stored anywhere.

Still if you're up to it, you're free to implement it and send me a patch. I suggest starting [here](https://github.com/KevinGoodsell/mork-converter) and [here](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Mork).

**Comment by DisposaBoy** [comment]
There is a parser for it, but if it doesn't work better than the sqlite databases and they don't work for chat (I've never used this feature) then it's probably not worth pursuing.

**Comment by gyunaev** [comment]
I have updated the parser, and the situation improved. Please see #21
