### ISSUE TITLE
QSocketNotifier: Can only be used with threads started with QThread

### ISSUE THREAD

**Issue by davepb16** [gyunaev/birdtray#138]
**OS**: 
Fedora 31 64bit.
**Birdtray version**: 1.6.0
**Thunderbird version**: 68.1.1
**Birdtray origin**: Github Source.
**Qt version**: 5.12.5 
**Description**

The Github version compiles fine but when I attempt to run it I get the error message:
"QSocketNotifier: Can only be used with threads started with QThread
Segmentation fault (core dumped)"

**Expected behavior**

Expected to run without error.
**To Reproduce**

1.  Download from github, compile and execute.

Edit:  This only seems to happen using Wayland.  If I switch back to X11 it runs fine.
I don't remember this problem occurring with Wayland when I was using Fedora 30.

**Comment by gyunaev** [comment]
Wayland is not supported yet.

**Comment by ThanosApostolou** [comment]
@davepb16 I think this is a Fedora 31 change to run all qt apps natively on wayland instead of xwayland. Try to use the xcb qt platform to fix this by running the app with 
```
birdtray --platform xcb
```

or add to your profile `export QT_QPA_PLATFORM=xcb` to run all qt apps in xwayland again (I also had problems with virtualbox and other qt apps when I tried fedora 31)

**Comment by gyunaev** [comment]
Essentially duplicate of #113
