### ISSUE TITLE
Unread count doesn't work with Owl account

### ISSUE THREAD

**Issue by AnthonyBarbier** [gyunaev/birdtray#166]
**OS**: Ubuntu 19.10 64bit x86 
**Birdtray version**:  1.6 
**Thunderbird version**: 68.1.2 
**Birdtray origin**: package manager (ppa:linuxuprising/apps) 
**Qt version**: _NA_ 

**Description**

I use Owl to access my company's Office 365 account so the path to the `msf` file is a bit different:
`~/.thunderbird/<profile>.default/webaccountMail/outlook.office.com/Inbox.msf`
The file on file seems to be getting updated every time I receive an email so it seems to be the correct file, however I never see the number of unread emails

**Expected behavior**

Number of unread emails displayed on top of the systray icon.

**To Reproduce**

1. 
2. 

**Screenshots**

**Additional context**

Running on i3-wm / gnome (Don't know if that's relevant)

**Comment by Abestanis** [comment]
Hi, I know a bit of time has passed since you created this issue, but if you are still interested in solving this, we are in the process of changing how we read the unread email counter from the mork files.

If you are able it would be awesome if you could test your `.msf` files with the changes proposed in #245. If you don't know how to compile Birdtray with these changes or if Birdtray still reports no unread emails with the new changes, please anonymize the corresponding mork files with [this Python script](https://github.com/gyunaev/birdtray/tree/master/contrib/anonymizeMork) and upload it here so we can test why it doesn't work. If you do so please also specify how many unread emails are shown in the Thunderbird UI for that folder.

**Comment by gyunaev** [comment]
Please provide the feedback whether the latest code fixes this issue, thanks!

**Comment by MarcinGmurczyk** [comment]
Hi, the issue still occurs for me with
- 5.4.33-3-MANJARO KDE
- Thunderbird 68.7.0
- birdtray 1.8.0
- ExQuilla for Exchange 68.1.1

As a date of 21 Apr these are the files with their modification date within .thunderbird directory

`27 Aug  2019  .thunderbird/<profile>.default/webaccountMail/outlook.office365.com.msf`

`21 Apr 12:22  .thunderbird/pqcmfmbk.default/ExQuilla/outlook.office365-1.com
 31 Mar 12:31  .thunderbird/pqcmfmbk.default/ExQuilla/outlook.office365-1.com.msf
 18 Dec  2019  .thunderbird/pqcmfmbk.default/ExQuilla/outlook.office365.com
 27 Aug  2019  .thunderbird/pqcmfmbk.default/ExQuilla/outlook.office365.com.msf`

So it seems that the one that is updated when email arrives  is  .thunderbird/pqcmfmbk.default/ExQuilla/outlook.office365-1.com

In the past I might use an Owl extension for a while so that explains [...]/webaccountMail/outlook.office365.com.msf file is present in the filesystem.

Moreover Exchange account is not visible in Birdtray settings
![image](https://user-images.githubusercontent.com/11760932/79855922-eada5b80-83cb-11ea-916d-67a73808ed29.png)

**Comment by MarcinGmurczyk** [comment]
Hi, the issue still occurs for me with
- 5.4.33-3-MANJARO KDE
- Thunderbird 68.7.0
- birdtray 1.8.0
- ExQuilla for Exchange 68.1.1

As a date of 21 Apr these are the files with their modification date within .thunderbird directory

`27 Aug  2019  .thunderbird/<profile>.default/webaccountMail/outlook.office365.com.msf`

`21 Apr 12:22  .thunderbird/<profile>.default/ExQuilla/outlook.office365-1.com`
`31 Mar 12:31  .thunderbird/<profile>.default/ExQuilla/outlook.office365-1.com.msf`
`18 Dec  2019  .thunderbird/<profile>.default/ExQuilla/outlook.office365.com`
`27 Aug  2019  .thunderbird/<profile>.default/ExQuilla/outlook.office365.com.msf`

So it seems that the one that is updated when email arrives  is  `.thunderbird/<profile>.default/ExQuilla/outlook.office365-1.com`

In the past I might use an Owl extension for a while so that explains `[...]/webaccountMail/outlook.office365.com.msf` file is present in the filesystem.

Moreover Exchange account is not visible in Birdtray settings
![image](https://user-images.githubusercontent.com/11760932/79856643-dfd3fb00-83cc-11ea-89e4-378ef6795493.png)

**Comment by Abestanis** [comment]
> In the past I might use an Owl extension

Would you be able to use a different Thunderbird profile (or alternatively delete the `<profile>` folder), set up the account again and report back on what files are present? So we can be sure which files are created by Thunderbird.

> Moreover Exchange account is not visible in Birdtray settings

Yeah, because the `ExQuilla` doesn't end with a `Mail`. We can easily add it to the list, but in the mean time you should be able to select the `.msf` files by holding `Ctrl` and `Shift` while you click on the `Add` button. This should open a file selection dialog where you can navigate to the folder and select the mork files (one at a time). Please report back if Birdtray is then able to read the correct unread counter from one of those `msf` files.

> So it seems that the one that is updated when email arrives is

If you don't close Thunderbird it never really closes the mork file, even trough it does write to it. This may explain why the modification date never changes. To make sure that Birdtray detects changes in that case, you might need to enable the `Force index file re-read every` option in the `Advanced` settings tab.

**Comment by MarcinGmurczyk** [comment]
> > In the past I might use an Owl extension
> 
> Would you be able to use a different Thunderbird profile (or alternatively delete the `<profile>` folder), set up the account again and report back on what files are present? So we can be sure which files are created by Thunderbird.
> 

These are .msf files present on the clean profile with ExQuilla Exchange account setup
`.thunderbird/<profile>.default-release/ExQuilla/outlook.office365.com/Inbox.msf`
`.thunderbird/<profile>.default-release/ExQuilla/outlook.office365.com/Jira.msf`
`.thunderbird/<profile>.default-release/ExQuilla/outlook.office365.com/Notes.msf`
`.thunderbird/<profile>.default-release/ExQuilla/outlook.office365.com/Junk.msf`
`.thunderbird/<profile>.default-release/ExQuilla/outlook.office365.com/Drafts.msf`
`.thunderbird/<profile>.default-release/ExQuilla/outlook.office365.com/Unsent Messages.msf`
`.thunderbird/<profile>.default-release/ExQuilla/outlook.office365.com/Reports.msf`
`.thunderbird/<profile>.default-release/ExQuilla/outlook.office365.com/Gitlab.msf`
`.thunderbird/<profile>.default-release/ExQuilla/outlook.office365.com/Trash.msf`
`.thunderbird/<profile>.default-release/ExQuilla/outlook.office365.com/Archive.msf`
`.thunderbird/<profile>.default-release/ExQuilla/outlook.office365.com/Conversation History.msf`
`.thunderbird/<profile>.default-release/ExQuilla/outlook.office365.com/Sent.msf`
`.thunderbird/<profile>.default-release/ExQuilla/outlook.office365.com.msf`

> > Moreover Exchange account is not visible in Birdtray settings
> 
> Yeah, because the `ExQuilla` doesn't end with a `Mail`. We can easily add it to the list, but in the mean time you should be able to select the `.msf` files by holding `Ctrl` and `Shift` while you click on the `Add` button. This should open a file selection dialog where you can navigate to the folder and select the mork files (one at a time). Please report back if Birdtray is then able to read the correct unread counter from one of those `msf` files.
> 

Birdtray is able to read correct unread counter when those files are selected by holding `Ctrl` and `Shift`. Neat trick, I think it should be documented in UI around that Add button.

Thanks for the help with setting things up!
