### ISSUE TITLE
Current command-line editor in advanced is kinda weird

### ISSUE THREAD

**Issue by gyunaev** [gyunaev/birdtray#183]
The way it is edited is a bit strange and doesn't allow copypasting complex command-lines. @Abestanis what would you say if we split it into two normal edit fields, one for executable (so it is taken as-is with all spaces) and one for the command-line arguments (which go space-separated)?

**Comment by Abestanis** [comment]
The reason I did it that way is to not have to deal with spaces in arguments, e.g `command argument="Arg with space"`.

**Comment by gyunaev** [comment]
I understand, but this is advanced settings tab; people opening it and modifying stuff there are expected to understand what they are doing.

Actually maybe we should use a single "Thunderbird command-line" edit line, and have a small state machine parser to properly convert into QStringList strings like "C:\Program Files\exe\thunderbird.exe" --profile test --title "My test profile"

**Comment by Abestanis** [comment]
Parsing commands is not a trivial task, think about escaped quotes `\"`, single quotes vs double quotes and so forth. If you really want to be able to paste complex command lines, we would have to implement a fully fledged command line parser.
I don't know if that is worth it. In my opinion, you should not need to interact with this dialog very often, so it might be ok if it is not as easy to use as the rest of Birdtray.

**Comment by Abestanis** [comment]
We could of course allow copy paste and just split on all spaces. Joining the parameters back together might be easier than having to enter each of them manually. That way we gain a little usability but don't add much complexity.

**Comment by gyunaev** [comment]
Actually a splitter is quite easy - see 18ad6c7..5f19eb2

**Comment by Abestanis** [comment]
I can't tell if that coveres all the corner cases, since I don't all the details of command line parsing and escaping myself. That is why I would use a libraries for this.

From what I could test, this looks good. A small problem with this implementation is that it writes back the escaped `\`, which we don't want. I think Qt will pass those straight to the process without unescaping them.

If we add this functionality, you should probably extract the dialog from `dialogsettings.cpp` into its own source file and implement it with a `.ui` file. I would then definitely split the command and arguments into two sections.

**Comment by gyunaev** [comment]
We only expect to pass the basic command-lines which we split properly (since we're not using shell). This is not for writing shell scripts :)
