### ISSUE TITLE
[Feature Request]: Option to start with Thunderbird minimized to tray.

### ISSUE THREAD

**Issue by tnilzon** [gyunaev/birdtray#23]
First of all I would like to give my complements to a very useful app, great!

Would love to see an option to have Thunderbird minimized into the tray when first launched, if that would be possible.

/Thanks

**Comment by JackDinn** [comment]
Already does have that option, although im not sure if its just on Linux ATM.
![screenshot_20181008_173043](https://user-images.githubusercontent.com/5557560/46621774-4ca3df00-cb20-11e8-9374-39cf06c05c5d.png)

**Comment by tnilzon** [comment]
Hi, no I don't see that option in my install. I am on Manjaro, and 
installed Birdtray v1.1 from the AUR repo.

See attached screen shot.


BR
Tomas Nilzon

**Comment by JackDinn** [comment]
install the birdtray-git or clone it from here and build it yourself to get the latest commit.

**Comment by tnilzon** [comment]
OK, I will try that.

Thanks


BR
Tomas Nilzon

**Comment by tnilzon** [comment]
Just tested it. Works like a charm, thanks!

**Comment by JackDinn** [comment]
just for info, to check for and then update a development repo (birdtray-git).
A decent AUR helper which will check the upstream repo for changes then trigger a package rebuild for you (e.g. aurman -Syu --devel, yay -Syu --devel) otherwise i don't think you will see any updates in the normal update notifications.

**Comment by tnilzon** [comment]
OK, thanks for the tip!


BR
Tomas Nilzon
