### ISSUE TITLE
BirdTray - Log File to show unread emails

### ISSUE THREAD

**Issue by RYRNRY** [gyunaev/birdtray#244]
Thunderbird : 68.3.0
O/S : Windows 7 64 bit
BirdTray : 1.7.0

BirdTray does not update the Email Counter once all the emails are read.  How do I enable logging to see which mail folder it thinks that there are unread emails ?

**Comment by RYRNRY** [comment]
Does BirdTray count emails in the JUNK-EMAIL folder causing the discrepancy in the unread count ?

**Comment by Abestanis** [comment]
Unfortunately it is currently only possible to view the debug output on Windows, if you attach to Birdtray with a debugger. #247 changes that, if you are able you can try and compile Birdtray with that patch. Otherwise, the easiest thing for you to do would probably be to remove the mail folders you are watching one by one and watch how it affects the unread counter.
But we are aware that there are problems with the unread counter and we are working on it. To keep up to date with our progress, see #245 and #217.

> Does BirdTray count emails in the JUNK-EMAIL folder causing the discrepancy in the unread count ?

Only if you specifically selected the folder to be monitored.

**Comment by gyunaev** [comment]
With the latest commit you should be able to see the logs in Settings -> Advanced -> Show Log Window button (settings then can be closed)
