### ISSUE TITLE
Uninstall problem

### ISSUE THREAD

**Issue by dragomang87** [gyunaev/birdtray#268]
**OS**: Windows 10, 64bit, updated to version 1909 after installation of Birdtray
**Birdtray version**: 1.7.0, installed as local user 
**Thunderbird version**: 74.0b2
**Birdtray origin**: windows installer from github
**Qt version**: _NA_ 

**Description**

Uninstall from windows "Apps and Features" after selecting he language says "There is no installation of birdtray".
The first time it did ask to confirm to kill the running Birdtray.

**Expected behavior**

It should uninstall or not appear in apps and features

**To Reproduce**

1. Install via windows installer, only for the current user 
2.  try to uninstall via "apps and features"

**Screenshots**

**Additional context**

**Comment by Abestanis** [comment]
Thank you for reporting this. This seems to be a longstanding Windows bug, that causes the uninstaller to be started with admin rights. That in turn causes the uninstallation of per-user installations to fail, because the unistaller looks in the `AppData` folder of the admin account instead of the `AppData` folder of the user.
This was [reported in 2017](https://github.com/Drizin/NsisMultiUser/issues/6) on the library that we use to handle this. Luckily they developed a fix that we can use, I'm currently testing if that solves the problem without introducing other problems.

As a workaround, you can start the uninstaller manually (the `uninstall.exe` in the Birdtray installation directory) or you can uninstall Birdtray via the `Programs and Features` page of the old Control Panel (not the new Settings App).

**Comment by dragomang87** [comment]
Thanks, the workaround also worked as expected.

**Comment by Abestanis** [comment]
Awesome, thank you again for your feedback and for your issue report!
