### ISSUE TITLE
Long period to switch status icon back to "no new mail" 

### ISSUE THREAD

**Issue by MaxAlekseyev** [gyunaev/birdtray#276]
I have one PNG icon icon for "no unread" and another one for "new mail" status. All messages were read, but "new mail"
icon is still presence in the tray. There two ways to change status to actual immidiatelly:
1. Setting -> Ok
2. Relaunch TB
**OS**: 
Win 10x64 1809 LTSC
**Birdtray version**: 
1.7.0 x 64
**Thunderbird version**: 
68.6.0 x 64
**Birdtray origin**: 
64 bit installer from https://github.com/gyunaev/birdtray/releases/tag/RELEASE_1.7.0

**To Reproduce**

1. Apply 2 different icons in General settings
2. Get the message and read it. The icon like freeze. I was waiting about 10 minutes.

**Comment by gyunaev** [comment]
Could you please build from the source? I just tested, it works fine for me.

@Abestanis shall release 1.8?

**Comment by MaxAlekseyev** [comment]
Abestanis  told about some library/enguine that I need to load SVG icons.
https://github.com/gyunaev/birdtray/issues/275

**Comment by MaxAlekseyev** [comment]
BTW, watching for this bug the whole day. Even turn on the native TB tray icon. Native icon is working absolutelly stable, situation with the BT is the same.

**Comment by gyunaev** [comment]
Actually, does only the unread icon remain (while the unread message counter disappears)? Or both the message counter and unread icon stay?

**Comment by MaxAlekseyev** [comment]
I turned off the counter. I'll turn on and report you.

**Comment by MaxAlekseyev** [comment]
1. I sent 2 messages from another account
2. Counter became 1, 2.
3. Clicked on first (read), still 2
4. The second - still 2.
5. Was waiting 20 min, nothing nad happened, still 2 (really 0).
6. Sent new message -> 1
7. Marked as read, 10 minutes - 1.

**Comment by gyunaev** [comment]
I guess you need a new build to test.

**Comment by MaxAlekseyev** [comment]
NP, let's try. Make it when you'll have a free minute. I'll make the detailed QA and send you report tomorrow.

**Comment by MaxAlekseyev** [comment]
The good news is the bug is absolutelly stable.

**Comment by Abestanis** [comment]
> Setting -> Ok

This does sound a lot like #95. The problem there is basically that due to the way Microsoft implemented the file watching functionality, Birdtray often doesn't get notified if the unread counter changes. What you are seeing, the icon not changing back, is a side effect of that (much like 
 #214). I will update bug #95 as soon as I have the time to do so. In the mean time, there is unfortunately not much you can do, but to close this bug and join the conversation on #95, once I revive it.

> @Abestanis shall we release 1.8?

We should do that soon, but I want to get a few things into master before that. Namely, I've been working on automatically creating the Windows installer on Github Actions. We also need to notify the translators, we said we would give them two weeks before we release.

**Comment by MaxAlekseyev** [comment]
Ok, do the best, will work as just the tray icon for now. The easiest way for quick accesss anyway.

**Comment by Abestanis** [comment]
Commit e4083ed might have fixed your issue. Can you try again with the latest `master`? You need to enable the `Force index file re-read every ...`  in the advanced tab of the settings.

**Comment by MaxAlekseyev** [comment]
At last in version 1.8.1 this issue woring Ok.

**Comment by Abestanis** [comment]
Awesome, thank you for the feedback.
