### ISSUE TITLE
Instructions on how to Compile / Build Birdtray on Windows platform

### ISSUE THREAD

**Issue by RYRNRY** [gyunaev/birdtray#277]
I am running Thunderbird v 68.3 on Windows 7 64 bit.

Are there any help docs on to download, build & test the BirdTray code on Windows.

Thanks.

**Comment by gyunaev** [comment]
The build instructions are in README, on the main project page. However those instructions expect you to already have a working Qt build environment installed, so they are not that useful for new users.

What you need to do is the following:

- Install Microsoft Visual C++ from https://visualstudio.microsoft.com/vs/community/ (a free community edition would work). Don't use an old version, it doesn't have C++14 which the current code uses. Expect to download ~3Gb.

- Install Qt: Go to https://www.qt.io/download, scroll down, "Download for open source users", scroll down, download the Qt online installer, run it. Make sure you check Qt Creator and your Visual Studio version. Expect it to download 2Gb.

- Run Qt creator, import CMakefiles.txt and click "Build".

**Comment by Abestanis** [comment]
You are also going to need to [download the sqlite3 library](https://www.sqlite.org/download.html) and tell cmake where to find it. You need `sqlite3.dll`, `sqlite3.lib` and `sqlite3.h`.
You can look at the [setup instructions for Github Actions]() as an example guide.

**Comment by gyunaev** [comment]
We might make it optional, and compile SQLite parser (and thus require the library) only if an option is passed to CMake. What do you think?

**Comment by Abestanis** [comment]
I don't think it is worth the effort. If someone wants to use the sqlite parser they could just check out an older commit where #294 is not merged. I am going to close this, because when #294 is merged, compiling on Windows is as easy as installing `cmake`, `Visual Studio`, `Qt` and the `Qt Creator` and then opening the [CMakeLists.txt](https://github.com/gyunaev/birdtray/blob/master/CMakeLists.txt) file.
