### ISSUE TITLE
Where to find the portable version (v1.7)?

### ISSUE THREAD

**Issue by tooomm** [gyunaev/birdtray#280]
Title says it all.

In the [release @github](https://github.com/gyunaev/birdtray/releases/tag/RELEASE_1.7.0), there are only install binaries for 32 and 64bit windows systems.

**Comment by gyunaev** [comment]
As far as I know, we do not provide portable versions.

**Comment by Abestanis** [comment]
No, we don't provide portable versions. On Windows, you can install Birdtray for the local user only without requiring admin rights. Does that fit your needs or why do you need a portable version?

**Comment by Abestanis** [comment]
I'm going to close this, because the installer already allows a portable installation. When installing, choose the installation for the current user only and change the installation path to the removable media. After installation, create an empty `birdtray.ini` file next to the `birdtray.exe`. When started, Birdtray will then use that file to store settings. In the next release, instead of `birdtray.ini` you need to create `birdtray-config.json`. If this is not helpful for you or if you encounter any problems, please reopen the issue.

**Comment by tooomm** [comment]
Could this be explained somewhere? How should users know about this?

**Comment by gyunaev** [comment]
Sure, it could be explained. Please write an explanation, and we'd be happy to add it.

**Comment by Abestanis** [comment]
@tooomm I'm working on improving the [README](https://github.com/gyunaev/birdtray/blob/master/README.md), we definitely want to add a section about portable installations there. Since you seem to use a portable installation or at least have an interest in it, it would be very helpful if you could tell me the main points that you would have wanted to know when you looked for information about a portable installation. Obviously, if you have the time and want to propose the full text of the section, that would be even better.

**Comment by tooomm** [comment]
>No, we don't provide portable versions. On Windows, you can install Birdtray for the local user only without requiring admin rights. Does that fit your needs or why do you need a portable version?

Admin rights are not a concern for me - mostly.
I happen to use several computers and always have my mails via portable Thunderbird at hand with my settings.
On my main PC it allows me to wipe and clean install my OS once in a while and don't have to deal with app installations and configuration at all.


>When installing, choose the installation for the current user only and change the installation path to the location or removable media of your choice. After installation, create an empty `birdtray-config.json` file next to the `birdtray.exe`. When started, Birdtray will then use that file to store settings.

This is basically the information that should be there in the repo somewhere at the very least. Probably the [installation section in the README](https://github.com/gyunaev/birdtray#installation)?
Ideally, those steps would be covered by the NSIS installer directly...
