### ISSUE TITLE
HiDPI/svg support

### ISSUE THREAD

**Issue by a-zurcher** [gyunaev/birdtray#303]
On my laptop running Debian KDE the birdtray icon its always very pixelated when I try to apply a new svg icon (see picture)
I have global scaling set to 1.5
![image](https://user-images.githubusercontent.com/52360674/78455967-78663d80-76a1-11ea-8e90-94dd90a56d53.png)
It it possible to fix?

**Comment by dvalter** [comment]
Currently (2020/03, should be rolled out in 1.8.0) Birdtray scales icon to 128x128. It works fine for high resolution raster icons (but it can be increased). However it does not work that well with vector icons since `QPixmap` rasterizes them with their nominal size (for examples /usr/share/icons/breeze/apps/16/kwrite.svg will be loaded as 16x16 pixmap).

#305 should fix this behavior by rendering svg directly to 128x128.
As a temporary workaround you may try to use a higher resolution icon (ideally 128x128) or convert it to 128x128 png manually.

**Comment by a-zurcher** [comment]
It now works, thank you!
