### ISSUE TITLE
Update birdtray installer was run in german on english Windows 10

### ISSUE THREAD

**Issue by Marat-Gumerov** [gyunaev/birdtray#321]
**OS**: Windows 10 64 bit, English localization
**Birdtray version**: 1.8.0
**Thunderbird version**: 68.7.0 64 bit
**Birdtray origin**: From chocolatey
**Qt version**: _NA_ 

**Description**

1. I saw dialog with recomendation to update my birdtray. I pressed "Update" button
2. Installation wizard window appeared. All texts were in German

**Expected behavior**

Installation wizard should be in english localization

**Additional context**

1. I had Russian Windows 10 when I installed Birdtray.
2. I installed english translation for Windows 10, from Windows Store and activated it.
3. I restarted my Windows some times
4. Then, after few days, I updated Birdtray

**Comment by Abestanis** [comment]
The installer lets you choose a language when you install Birdtray the first time. It then remembers your choice and picks it by default the next time.
You can view (and delete) your choice by reading the following key in the Windows registry: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Birdtray\Language`
If you installed Birdtray for the current user only, the key would be:
`HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Birdtray (current user)\Language`
The value of the key is a number representing the language (e.g. `1033` for English and `1031` for German. [Full list](https://www.science.co.il/language/Locale-codes.php)). Could you please report back what value is stored at that key in your registry?

Is it possible that you choose German as the Language when first installing Birdtray. You mentioned that you installed Birdtray via `chocolatey`, did you get the graphical installer interface when doing so? Or was it a silent install?

My guess is that it was a silent install and that the installer automatically choose the first entry in the list of languages for you. Because they are sorted alphabetically after their language tag (`de` for German), German is currently on the top of the list and was probably chosen by default.

Could you please report back if you installed Birdtray with or without a graphical installer?

**Comment by Abestanis** [comment]
> Could you please report back ...

Disregard that, I was able to reproduce this.
By the way, thank you for bug report and for filling out all of the information, that helped a lot!

The fix is to not save an installer language at all if Birdtray is installed in silent mode, e.g. without a graphical window popping up. Unfortunately, this does not fix the problem if you installed any Birdtray version before the upcoming `1.8.1` release. Your best bet is to either delete the registry key  I mentioned above, or uninstall the older Birdtray version (you can keep your settings) and to install the `1.8.1` version of Birdtray that will include the fix.

**Comment by Marat-Gumerov** [comment]
Sorry, I did not report back in time.
chocolatey always installs applications in silent mode, so yes, it was a silent install.
Thank you for the information about how to fix it. And thank you for such a great application!

**Comment by Marat-Gumerov** [comment]
> The value of the key is a number representing the language (e.g. `1033` for English and `1031` for German. [Full list](https://www.science.co.il/language/Locale-codes.php)). Could you please report back what value is stored at that key in your registry?

I also checked this value and it was 1031
