### ISSUE TITLE
Setting for new mail icon resets with each launch

### ISSUE THREAD

**Issue by Vexz00** [gyunaev/birdtray#356]
In the general options tab is a checkbox which you can activate and then choose a tray icon that gets displayed if you have unread emails.
I activated this option but each time I exit Birdtray completely and start it again this setting is unchecked and I have to activate it again.

Windows 10 1909 x64
Birdtray x64
Thunderbird 68.7.0

**Comment by Abestanis** [comment]
I can not reproduce that on my Windows 10 machine. Which version of Birdtray are you using?

Do you actually choose a different icon (with the `[…]` button) or do you just click the checkbox? If you don't chose an icon, the setting doesn't have any effect and will reset.

**Comment by Vexz00** [comment]
I use Birdtray 1.8.1 which I think is the latest version.
Yes, I set a custom icon. And it works just fine until I exit Birdtray. The next time I start it the checkbox is unchecked again.
Is there some kind of log that I can send you to identify the problem?

**Comment by Abestanis** [comment]
You can access the log via the `Show log window` in the `Advanced` tab. The log will probably not be enough because we don't log anything related to the settings. Could you please also provide your [config file](https://github.com/gyunaev/birdtray#configuration-file-location). If possible, please upload a copy of the config file while Birdtray is running and displaying your configured icon. If the contents change, please also upload a copy after you close Birdtray and one after you opened Birdtray again.

**Comment by Vexz00** [comment]
Here are the configs - though it looks to me like they didn't change at all.

Running and with the custom icon enabled:
https://u.teknik.io/8LkMB.json

While closed:
https://u.teknik.io/zYXDw.json

Started again:
https://u.teknik.io/iBROY.json

Log (I changed my username for privacy reasons):
https://p.teknik.io/Km3D2

**Comment by Abestanis** [comment]
Thank you for providing all of that information.
Your log indicates that Birdtray is detecting no unread emails. You said
> it works just fine until I exit Birdtray.

Do you see the new icon you selected in the system tray? If not, try if it actually shows the new icon if you have unread emails.
Your settings files didn't contain an unread icon, so it isn't saved. Did you click the check mark in addition to selecting the icon? If the check mark is not set, the icon will not be saved. You are not supposed to select an icon if the check mark is not enabled, so that is definitely a bug.

If it is not that, then I am going to need a step by step guide on what you do to reproduce the problem (e.g. which buttons do you click, etc.), preferably with a screenshot of the Birdtray window and tray icon for each step. Windows includes a program called `Steps Recorder` that you can use.

**Comment by Vexz00** [comment]
> Do you see the new icon you selected in the system tray?

Yes. Like I said: It works just fine until I exit Birdtray.

> Your settings files didn't contain an unread icon, so it isn't saved.

Can I manually edit the config file and insert the path to the icon that should get displayed? If yes: Can you please give me an example of what it should look like? I'd be fine with that because it sounds to me like it's a problem only I have and it has to do with the combination of my computer and Birdtray.

> Did you click the check mark in addition to selecting the icon?

The option to select an icon is greyed out if the checkbox for this option is not checked. So yes, I'm forced to check the box first if I want to select an icon.

> If it is not that, then I am going to need a step by step guide on what you do to reproduce the problem (e.g. which buttons do you click, etc.), preferably with a screenshot of the Birdtray window and tray icon for each step. Windows includes a program called `Steps Recorder` that you can use.

My OS is in German so the result of the Steps Recorders is also in German. So I will write down my steps myself.

1. Open the start menu.
2. Click on Birdtray to start it.
3. Right click on the tray icon of Birdtray and select "Settings...".
4. Click on the checkbox for "Different icon when unread:".
5. Click on the button to browse for the icon and select it. (The file's path is "C:\Program Files\Birdtray\mail-unread.png")
6. Click the OK button to close the settings menu.

Now it's all working. But if I restart my computer or right click the tray icon of Birdtray and select "Quit" and then restart Birdtray like in steps 1 to 3 from above the checkbox for "Different icon when unread:" is again unchecked.

**Comment by Abestanis** [comment]
> My OS is in German so the result of the Steps Recorders is also in German.

That wouldn't have been a problem, I'm a German myself. 😃
The steps you take all seem to be correct. I really need to be able to reproduce this, otherwise I have no clue where the problem might come from. Could you upload the `mail-unread.png`? I can't access the settings file anymore, could you upload it again? The log file is also no longer accessible, would it be possible to upload a new one where you have an unread email and execute the steps you described above?
Thank you for providing all of that information and sorry it is taking so long.

I would also be interested to know what happens if you change any other setting in addition to the unread icon. Are the other changes saved and survive the restart ob Birdtray?

> Can I manually edit the config file and insert the path to the icon that should get displayed?

Hm, it's not trivial, because we don't save the path to the icon in the config, but the actual icon itself in a textual representation. Much like the `"common/notificationicon": "<LETTERS>",` entry, you would need a `"common/notificationiconunread": "<LETTERS>",` entry. You could do the following:
1. Make a backup of your configuration file.
2. Choose the `mail-unread.png` as the main icon in the Birdtray settings.
3. Close the Birdtray Settings with the Ok button and exit Birdtray.
4. Edit the configuration file with an text editor and copy the  `"common/notificationicon": "<LETTERS>",` below itself, change the `common/notificationicon` to `common/notificationiconunread`. Save the file.
5. Start Birdtray. It should read the unread icon from the config. You can then reset the main icon in the settings.

I'm hoping it won't reset the unread icon when you save the settings in step 5, but I guess we'll see.

**Comment by Vexz00** [comment]
> Could you upload the `mail-unread.png`? I can't access the settings file anymore, could you upload it again? The log file is also no longer accessible, would it be possible to upload a new one where you have an unread email and execute the steps you described above?

Running Birdtray with unread email and my icon displayed:
https://u.teknik.io/Bc7bd.json

Quitted Birdtray:
https://u.teknik.io/OP5Va.json

Birdtray started again:
https://u.teknik.io/SqjhR.json

Log:
https://u.teknik.io/A8Ozf.txt

mail-unread.png file:
https://u.teknik.io/Ux44U.png

The links should be available for 2 months.

> Thank you for providing all of that information and sorry it is taking so long.

No problem. I know some problems cannot get fixed within a minute. ;)

> I would also be interested to know what happens if you change any other setting in addition to the unread icon. Are the other changes saved and survive the restart ob Birdtray?

I checked the option for the custom icon for unread emails and in addition made changes to the following settings under the following tabs:
General: Blinking speed
Monitoring: Checked "Allow ignoring the current unread email counter" (was unchecked before)
Hiding: Unchecked "Start Thunderbird when Birdtray starts" (was checked before)
New Email: Unchecked "Enable New Email submenu" (was checked before)
Advanced: Unchecked "Force index file re-read every 5 seconds" (was checked before)

**Result:** All changes were saved after a restart of Birdtray except of course the custom icon option. So it appears to be just this option that isn't saved for me.

> Hm, it's not trivial, because we don't save the path to the icon in the config, but the actual icon itself in a textual representation. Much like the `"common/notificationicon": "<LETTERS>",` entry, you would need a `"common/notificationiconunread": "<LETTERS>",` entry. You could do the following:
> 
> 1. Make a backup of your configuration file.
> 2. Choose the `mail-unread.png` as the main icon in the Birdtray settings.
> 3. Close the Birdtray Settings with the Ok button and exit Birdtray.
> 4. Edit the configuration file with an text editor and copy the  `"common/notificationicon": "<LETTERS>",` below itself, change the `common/notificationicon` to `common/notificationiconunread`. Save the file.
> 5. Start Birdtray. It should read the unread icon from the config. You can then reset the main icon in the settings.

Well on the next start of Birdtray the setting for the custom icon is checked which is good. But now when I change the icon again to mail-unread.png, click on the OK button and restart Birdtray the setting is again unchecked. Is there some way I can convert the path with the filename of the mail-unread.png to those letters so I can copy them in the config file?

**Comment by Abestanis** [comment]
YES! I am able to reproduce the problem using your icon! 🎉

**Comment by Abestanis** [comment]
Ok, so the png seems to contain an incorrect color profile. We are able to read it, but libpng is refusing to save it and returns an empty string and emits these messages:
```
libpng warning: iCCP: known incorrect sRGB profile
libpng error: known incorrect sRGB profile
```
I guess the image is old or was created with an old program. A quick fix is the open the file in an editor (except `paint`, that didn't work) and save it again.
This image works for me, you should be able to download it and use it instead of your original image: 
![mail-unread - new](https://user-images.githubusercontent.com/6966049/80927243-b9369c80-8d9c-11ea-98b8-55b308db5823.png)
I will have to look into what we can do about this, we should at least display a warning or something. Thank you again for taking the time and providing all of the information, we would not have been able to solve this without it.

**Comment by Vexz00** [comment]
Your image works for me. I'm glad to help and thanks to you too. Never would I have thought the color profile of this icon is the issue.
