### ISSUE TITLE
QObject::~QObject: Timers cannot be stopped from another thread

### ISSUE THREAD

**Issue by dreadful-itconsultant** [gyunaev/birdtray#368]
**OS**: Windows 10 64Bit 
**Birdtray version**: 1.8.1 
**Thunderbird version**: 68.8.0 
**Birdtray origin**: From installer 
**Qt version**: _NA_ 

**Description**
When start birdtray.exe over dos commandline or powershell commandline, then not close commandline windows automatic. When close commandline windows manualy, then get error "QObject::~QObject: Timers cannot be stopped from another thread" in the commandline windows and birdtray will exit.
With previous version 1.7.0 work fine.

**Screenshots**

![image](https://user-images.githubusercontent.com/65395169/82037876-0a029b00-96a3-11ea-9edc-caeb54ea35d1.png)

**Additional context**

The commands are:
Start /D "C:\Program Files\birdtray" /B birdtray.exe
and
powershell.exe -command "& 'C:\Program Files\Birdtray\birdtray.exe"'

Best regards

**Comment by Abestanis** [comment]
I just tried this and I can't reproduce it.
Is this still a problem for you? There will be a new release in a few days, maybe you can try if it was fixed.
Otherwise you need describe the steps you take in more detail.

Here is what I did to try to replicate the problem:
1. Open a command prompt.
2. Execute `Start /D "C:\Program Files\birdtray" /B birdtray.exe -l stderr`
3. Execute `exit`.
What happened:
The cmd window was kept open, until I close Birdtray via the system tray. I don't see the warning mentioned above.

Out of curiosity, why do you need to start Birdtray in such a complicated way?

Also, is it just the warning that is the problem for you? And with `With previous version 1.7.0 work fine.` you mean, that the warning didn't show up with Birdtray 1.7.0?
