### ISSUE TITLE
Permanent CPU load ~8% on Win10

### ISSUE THREAD

**Issue by MaxAlekseyev** [gyunaev/birdtray#372]
Hi,

Birdtray 1.8.1
TB 68.8.0
Win10x64 1809 LTSC

Everething working well accept of permanent ~8% CPU load by the process.

**Comment by gyunaev** [comment]
Anything in the logs?

**Comment by Abestanis** [comment]
I'm guessing you have the option `Force index file re-read every x seconds` active in the advanced settings. That will cause a bit of CPU load, because it has to go through all of your mork files every x seconds.

If you don't have that setting enabled but still experience that CPU load, please reopen this issue and upload a Birdtray log and your configuration.
