### ISSUE TITLE
Just show the number of new messages, instead of counting unread ones.

### ISSUE THREAD

**Issue by Grimmwicht** [gyunaev/birdtray#377]
Hi,

would it be possible for Birdtray to just show the number of **new** messages, instead of counting **unread** ones? I like this little tool, but I'm used to set some mails to unread again after reading, to deal later with them, or ignoring them completely, e.g. personal mails that I will handle in the evening at home.

Thunderbird already uses this distinction, so this may possibly just a small code change, but would make me very happy. Thanks for the good work so far!

Cheers!

**Comment by tomas-chrastina** [comment]
+1 

Such feature is essential also for my kind of email "workflow".

For now it's just about configuring it to **Allow ignoring the current unread email counter** and **Ignore unread emails at startup**. But I have to manually click **Ignore unread emails** from tray a lot of times. And it's just exhausting.

Thank you in advance for considering this.

**Comment by gyunaev** [comment]
Birdtray doesn't know and has no way to know whether it is a new message (which you never read) or whether you have read it, and then made unread again. So I don't understand how to achieve this.

For example, if you are reading an email and a new email was just received, how would Birdtray know what happened?

**Comment by Grimmwicht** [comment]
That depends on how Birdtray recognises unread messages. Do you just read TBs database, or can you see every single mail and its state?
Birdtray could remember a list of new messages (or hashes), so it would know: *„Ah, the mail with this particular subject and from this particular sender – I already told my user yesterday, that this mail is new. I guess I shouldn't bother him again now.”*

**Comment by gyunaev** [comment]
I see every single email and its state. However what you suggest would require having another database in Birdtray, which would track the email states (and it would have to remember ALL read email states, i.e. a history of everything you ever had in the inbox). Because we don't want it to grow indefinitely, it has to be somehow rescanned and cleaned periodically, and so on.

This is very complicated implementation, and the functionality it would provide is very minor and too suited to your particular unique use case. So the chance of this to be implemented is pretty much zero, I wouldn't probably even accept a such complicated pull request. Sorry for that.

**Comment by tomas-chrastina** [comment]
Maybe my request is quite different than the one from @Grimmwicht.
What will work for me is to automate it like this:
- even now, you can check new unread e-mail by some delta/timestamp, when **I set Ignore unread emails at startup**
- so for me cycle like this can work
1) There is need to set some initial value of "last check" (it is in some way there even now)
2) When new e-mail is detected, display number of unread, like it is possible even now
3) When I press Tray icon = Navigate to Thunderbird window, automatically reset "last check" value. Basically automatically display Thunderbird window and press **Ignore unread mails** (maybe it even now reset this kind of "last check" stamp).

This way I can see number of new and unread e-mails from the moment I last opened Thunderbird window. And also the same way as you hide number when I manually set e-mails to read, hide tray icon. So tray icon will be displayed unless all new and unread messages (detected as delta) are set to read, or I open Thunderbird window from tray icon.

**Comment by gyunaev** [comment]
Please try the current build, there is a new setting in Hiding menu at bottom.

**Comment by gyunaev** [comment]
>     3. When I press Tray icon = Navigate to Thunderbird window, automatically reset "last check" value. Basically automatically display Thunderbird window and press **Ignore unread mails** (maybe it even now resets this kind of "last check" stamp).

Please try the new build, there is a new setting in Hiding menu.

**Comment by tomas-chrastina** [comment]
> > 1. When I press Tray icon = Navigate to Thunderbird window, automatically reset "last check" value. Basically automatically display Thunderbird window and press **Ignore unread mails** (maybe it even now resets this kind of "last check" stamp).
> 
> Please try the new build, there is a new setting in Hiding menu.

It took me a while to get back here.

Point 3 is working.

But it is working the other way around. What would help in current situation to cover both scenarios would be another option:
"When clicking on Birdtray icon to **show** Thunderbird, reset the icon by ignoring all currently unread emails."

Because my request is for this "workflow":
1) Thunderbird is minimized, Birdtray is set to "hide it if no new mail is present". So in normal run when there are no new messages, tray icon is hidden, and Birdtray is checking in the background.
2) New email is detected => Birdtray icon is displayed.
3) I click Birdtray icon => show Thunderbird to check emails. **Now I'd like to reset counter.**
4) I minimize Thunderbird by clicking windows "X". I have extension "Minimize on Close" so Thunderbird will keep running.
Also by setting Birdtray to "Hide Thunderbird window when it is minimized" it can be hidden in a second from taskbar in this scenario.

So this is different from current scenario, when I need to click Birdtray icon explicitly again, to reset the counter.

Thank you in advance.
