### ISSUE TITLE
"Fix" button grayed out

### ISSUE THREAD

**Issue by JBroki** [gyunaev/birdtray#39]
I have built birdtray 1.4 from source (Ubuntu 18.04.1, KDE 4.14.38, Thunderbird 60.2.1) and want to reset the counter (it shows a number with about 10 digits, I can't read it). The button to fix this grayed out, though. Did I miss something that could solve the problem?
Thank you!

**Comment by gyunaev** [comment]
When using Mork parser, you cannot fix it in Birdtray. Instead you should right-click on the monitored folder in Thunderbird, and select "Mark Folder Read". Let me know if it helped.

**Comment by JBroki** [comment]
Unfortunately, selecting "Mark Folder Read" didn't help... But I could figure out that it is not a general problem - it is restricted to one of my three email accounts. I tried removing this account and adding it again but it didn't change anything. I don't know what's the (technical) difference between this account and the other ones, so I don't know where to look for the reasons of my problem. Any ideas?

Besides: I really like birdtray and admire the work you have done. Great job!

**Comment by jtrulson** [comment]
FWIW, I saw this same error today for a google account.  It would show a large (impossible to read) number in the unread counter icon.

Marking everything as read did not affect anything.

I went to the first email in that INBOX -- it was about a year old.  I archived it, and then suddenly I saw in the console (where birdtray was started):

```
Triggering the unread counter update
Unread counter for ...<deleted-for-privacy>... ImapMail/imap.googlemail-1.com/INBOX.msf: 0
unreadCounterUpdate 0
```

And the counter went back to 0.

Hope that helps.

**Comment by gyunaev** [comment]
If marking folder read doesn't help, please first mark one or more emails as unread (select email, right click and choose "Mark as unread"). Then mark the whole folder read.

**Comment by psposito** [comment]
Hi guanev,

I am facing the same issue....

Unfortunately marking folders and/or emails, as per your above advice, does not help.

The tray icon is blinking and showing a big number of unread emails..

[![Bird-Tray1.png](https://i.postimg.cc/QMfhzTVS/Bird-Tray1.png)](https://postimg.cc/SXYB2j6z)

Ever since the "Fix" Button is inactive, I am not aware of what to do...

[![Bird-Tray2.png](https://i.postimg.cc/jqXLbLmV/Bird-Tray2.png)](https://postimg.cc/0rz8G29Z)

Awaiting your further assistance

Thank you!
