### ISSUE TITLE
Unread counter stays at 1 when all mail is read

### ISSUE THREAD

**Issue by airbete** [gyunaev/birdtray#41]
For one of the monitored account, the unread count won't go to zero. When I have no unread mail, it shows 1. When I have 1 unread mail, it shows 2. Etc.

I have tried the Fix button after having closed Thunderbird first, but the problem persists. I even tried to remove that account completely and then add it again, but still no change.

AB.

**Comment by gyunaev** [comment]
Are you using Mork parser or sqlite parser? Which version of birdtray?

**Comment by airbete** [comment]
I'm using Mork.
Birdtray version is 1.3:
`git log -1`
commit ab86e29d3b8d621d165bdf6d1edddf41e06e8d06 (HEAD -> master, origin/master, origin/HEAD)

**Comment by gyunaev** [comment]
Can you delete this MSF file and restart thunderbird? If it still prints "invalid format", can you share this file with me, privately if needed?

**Comment by atomGit** [comment]
i've had this same problem with 1.3 since i started using BT - i'll be watching 1.4 to see if it does the same

what i found is that if you open the settings -> monitoring tab and just click 'ok', BT sets the count to 0 again and all is ok until the next time - doesn't matter what file i monitor or whether its POP or IMAP, BT always fails to reset the count eventually when left running long enough, though i suppose this could be a TB problem too as i've noticed it acting up when left running long enough, like ignoring the default mail account when checking mail

the 'fix' button has always been disabled for me

**Comment by tryfon** [comment]
In my case (BirdTray 1.5 on Ubuntu 18.04.2) the Fix button is disabled and I can't find any way to work around this. Any help from the developers?

**Comment by atomGit** [comment]
the 'fix' button is always disabled for me as well, but give this a try: open the settings, then click the 'monitoring' tab, then click 'ok (no need to do anything else) - that always fixes the unread count for me

**Comment by tryfon** [comment]
Thanks atomGit, but this workaround is not working in my case.

**Comment by brunt82** [comment]
Have you tried to "repair" your msf-file?

Open properties of the mail folder within Thunderbird (e.g. "Inbox") and click on "repair". This may take a while dependent of the mail count.

Of course you should repair all folder which are monitored by birdtray.

**Comment by tryfon** [comment]
Yes, repair worked! Thank you very much! Perhaps you could integrate this functionality to BirdTray's interface somehow.

**Comment by brunt82** [comment]
I'm no developer, only user. But I cannot imagine how to integrate such a function into birdtray except by adding an advice / comment anywhere.

**Comment by airbete** [comment]
> Have you tried to "repair" your msf-file?
> 
> Open properties of the mail folder within Thunderbird (e.g. "Inbox") and click on "repair". This may take a while dependent of the mail count.

@brunt82, your suggestion worked for me too. Thank you!
