### ISSUE TITLE
stop unread notify when TB is displayed (feature)

### ISSUE THREAD

**Issue by atomGit** [gyunaev/birdtray#42]
i often like to leave mail marked as unread so they draw my attention later, however i would like birdtray to cease notifying of unread mail once i un-hide TB and not notify again until the next mail arrives

in other words, detect the TB window state and, if visible, set the unread count to 0 and wait for new mail

**Comment by atomGit** [comment]
that's an even better approach than what i suggested :)

**Comment by gyunaev** [comment]
I'm unsure what is the exact logic described here. Can you please provide more detailed workflow, step by step: what exactly you'd be doing, and what exactly you expect?

**Comment by s-moch** [comment]
scenario 1: "Hide/show Thunderbird window when clicking on tray icon" disabled
- icon displays e.g. 10 unread emails
- click on icon
- icon changes to "no unread email", window unchanged (because hide/show disabled)
- new email arrives
- icon changes to "unread email", ideally showing 1 new email (not 11)
- reading e.g. 4 of the 11 unread emails
- icon changes to "no unread email"
- new email arrives
- icon changes to "unread email", ideally showing 1 new email (not 8)

scenario 2: "Hide/show... enabled
- same behavior as above (reset unread mail count), but also hiding/opening TB window when clicking on icon

Would be great to get a config option for this counter reset, maybe others could become confused when the displayed unread mail count seems to be wrong.

**Comment by atomGit** [comment]
> Suppress current unreads

i'm not exactly sure what you mean with that - i think what s-moch and me are wanting is a way to be notified of only new mail and not any existing unread mail which is i think what you're getting at with such an option??? here's what i'm looking for, which is the same as s-moch i believe...

* new mail arrives - icon flashes
* i don't read the mail (or don't mark it read), but i want to end the notification
* more mail arrives - icon flashes again

so the problem is how to detect that i want the notification to end - by an icon click? detect TB window visible state? icon right click and click a 'reset' menu item? personally i don't think i care

i haven't really thought about it, but it seems like the r-click context menu item might be the easiest/best?

**Comment by s-moch** [comment]
Thank you for implementing this feature.

The context option is not as easy to use as a direct click, but it works. Background: I don't want to use this show/hide feature, so the direct click would be the easiest way for me to reset the counter.
(Btw, when I disable the show/hide option, why is the icon click not ignored, and the TB window still opens/closes?)

There is some strange behavior when reading previously unread email:
- 10 unread emails
- I reset the counter
- no unread email displayed, great.
- 2 new emails arrive, unread count set to 2, great.
- I read one email, unread count set to 1, OK. Could be set to zero, but maybe a matter of taste.
- I read another email, count set to zero, great.
- I read another email, count set to 9, strange. Can you please reduce the saved ignore-count instead, so that I still see no unread email?

Thanks again for your effort!

**Comment by gyunaev** [comment]
This is how it is implemented, as there is no other way to "unset" the unread. The way it works, if you start reading your emails, and go below the "suppressed" count, it would then disable suppression.
