### ISSUE TITLE
Birdtray does not see any profiles - only empty folders when setting up (flatpak)

### ISSUE THREAD

**Issue by Chatron** [gyunaev/birdtray#437]
Hello, 

may someone can help me out. I'm using
Manjaro
Thunderbird 68.12 (installed form repository)
Birdtray 1.9 (installed form flatpak)
When i try to setting up Birdtray adding the profile folder, i can only see empty folders. No mater witch folder i choose, Birdtray does not recognize it as profile location. 
Am i doing something wrong?

My profiles.ini is located under
`/home/user/.thunderbird`
and has this

```
[Profile0]
Name=User
IsRelative=0
Path=/home/user/Documents/.pers_data/Thunderbird_Profile/thunderbird_profile_maildir
Default=1

[General]
StartWithLastProfile=1
Version=2

[InstallFDC34C9F024745EB]
Default=/home/user/Documents/.pers_data/Thunderbird_Profile/thunderbird_profile_maildir
```

But when I try choose the folder
`/home/user/Documents/.pers_data/Thunderbird_Profile/`
or
`/home/user/Documents/.pers_data/Thunderbird_Profile/thunderbird_profile_maildir`
it dont see any file or profile, only empty folder and Birdtray does not let me ad none of this folders.

Are I'm handling it wrong?

Thank you very much for your time.

**Comment by vadimhp** [comment]
Same here. I have Ubuntu 18.04 and installed with flatpak.
When I click **Browse** to select the profiles folder, I'm unable to browse to `/home/username/snap/thunderbird/common/.thunderbird/`. The browse dialog isn't displaying all the folders that I can go though. Here's a screenshot: [https://imgur.com/a/49bEADs](url)

Also, when I type out the path manually, nothing happens: [https://imgur.com/a/DuaAsD2](url)

**Comment by Abestanis** [comment]
@Chatron Birdtray does not read the `profiles.ini` file, because the format is not standardized and could change without warning. As mentioned in #393 ([comment](https://github.com/gyunaev/birdtray/issues/393#issuecomment-703170164)), Birdtray is expecting a standard layout of `<Profile Directory>/ImapMail/<AccountName>`. You then select the `<Profile Directory>` in the `Add`-dialog.

You can either change the directory layout so it matches what Birdtray expects, or you could use the alternative dialog (hold <kbd>Ctrl</kbd>+<kbd>Shift</kbd> when clicking the `Add` button) and select the `.msf` files directly.

Please reopen if you need further assistance.

@vadimhp Because we are using the system file dialog, we can't control showing hidden directories from Birdtray (see #109). You must find the setting in your file dialog to show hidden files, e.g. for Ubuntu 20.04 you can bring up this menu by right clicking and enable the option from there:

![Right click menu in the file chooser dialog on Ubuntu](https://user-images.githubusercontent.com/6966049/104791421-e300e980-579a-11eb-8366-e28e6ad477ec.png)

Alternatively, if you can't find such an option on your system, navigate to the directory with your file explorer, copy the path and paste it into the `Add`-dialog manually.
