### ISSUE TITLE
Autostart not working

### ISSUE THREAD

**Issue by yoshegg** [gyunaev/birdtray#46]
Using Ubuntu 18.10, birdtray won't start if put into startup applications. 

The following message can be found in `/var/syslog`:
`Sorry, system tray cannot be controlled through this addon on your operating system`

Maybe birdtray is started before the gnome-shell's system tray is loaded?

**Comment by yoshegg** [comment]
A workaround is to use the following command as startup command: 
`bash -c "sleep 20 &&  /usr/bin/birdtray"`

**Comment by vedgy** [comment]
Hi @gyunaev,
I just got this error message on my Manjaro Xfce desktop after large system upgrades. I think that *birdtray* doesn't wait sufficiently long for the system tray to become available due to the following mistake in code:
according to the comment at the top of [`ensureSystemTrayAvailable()`](https://github.com/gyunaev/birdtray/blob/18623475d6f20e2ecbd7aa8b4e91032fe0b535a2/src/main.cpp#L15), this function is supposed to wait for up to 60 seconds. But it calls [`QThread::usleep( 500 )`](https://doc.qt.io/qt-5/qthread.html#usleep) for up to 120 times. (500 microseconds) * 120 = 60 milliseconds. I think that [`QThread::msleep( 500 )`](https://doc.qt.io/qt-5/qthread.html#msleep) should be called instead, though I haven't actually tried or tested such a change.

**Comment by gyunaev** [comment]
Yes, correct. Fixed.
