### ISSUE TITLE
Monitor accounts on a different hard disk

### ISSUE THREAD

**Issue by shmu26** [gyunaev/birdtray#460]
Kubuntu 20.10
Thunderbird 78.8.0
I moved the storage location of my Thunderbird mail accounts to a different hard disk (NTFS).
When I try to add them in Birdtray, I am unable to open the folder containing them. I see the folder, but it doesn't open. 
Thunderbird itself works as expected.

**Comment by Abestanis** [comment]
You might have the same issue as #393 where your new Thunderbird profile does not have the folder structure that Birdtray expects. Have a look at my [comment](https://github.com/gyunaev/birdtray/issues/393#issuecomment-703170164) for a solution to that problem.

If it is something different we will need a more descriptive explanation on what you are seeing and what doesn't work as you expect. It's not really clear what you mean with `it doesn't open`. What exactly does not open? Screenshots would also help us to determine your problem.

Also, we didn't create the issue template to make it harder for you to file a bug, but because the information we request there is vital for us to solve your issue. For the future and also for other projects, please don't ignore the template and just fill out the information. Now I have to ask you to provide the following information in addition to a better problem description if you want us to be able to help you:

* Your Desktop manager (e.g. KDE, Gnome, ...)
* Birdtray version
* How you installed Birdtray and if you compiled it yourself, the Qt version you used.

**Comment by shmu26** [comment]
You nailed it. Indeed, the folder structure was modified. Your solution works:
"If you hold the keys Ctrl and Shift when clicking the Adicionar button, you get a file chooser dialog where you can directly choose the .msf files to watch."

**Comment by Abestanis** [comment]
I'm glad I could help. 👍
