### ISSUE TITLE
If using "minimize on close" add on, thunderbird is not really quitting

### ISSUE THREAD

**Issue by thegarlynch** [gyunaev/birdtray#477]
**OS**:  Void Linux (glibc)
**Linux Desktop Manager**: Gnome 40 (Wayland)
**Birdtray version**: 1.9.0
**Thunderbird version**: 78.12.0
**Birdtray origin**: Package Manager xbps
**Qt version**: _NA_ 

**Description**

I am using minimize on close add on, off course that are going to overwrite close function. but i hope thunderbird has a way to made it really really closing. i don't know, maybe the current implementation is using forked thunderbird process or probably dbus? you could set it to truly exit if that was the case

**Expected behavior**

Closing for real

**To Reproduce**

1. Install Minimize on Close add on
2. Right Click Tray of birdtray
3. Select Exit

**Comment by gyunaev** [comment]
This is because the addon intercepts the _NET_CLOSE_WINDOW message but does not close. It is possible to "close" Thunderbird by other means (for example killing its process), but this would prevent it, for example, to ask you whether you want to save an unfinished email, or doing some internal things.

D-bus, etc - too much effort to handle a very narrow use case, sorry.
