### ISSUE TITLE
Ability to assign keyboard shortcut to show/hide

### ISSUE THREAD

**Issue by vlatkoB** [gyunaev/birdtray#48]
Hi, I have assigned a keyboard shortcut for launching TB, but when I launch it with that key, the "link" between Birdtray state of TB and the real state of TB seems to be lost, and the only way to "link" them again, so Birdtray can minimize and show TB again, is to click the icon couple of times.
After activating TB with the key, there are no two TBs active, only the same one.

It would be nice if we could bind a key to, say, `birdtray --show/hide` so Birdtray would do the same action as clicking on its icon, i.e. know what the current state of TB is and manage it.

Is something like that maybe already possible? What do you think?

**Comment by gyunaev** [comment]
Note that you can hide Thunderbird without birdtray, i.e. by using xprop.

**Comment by vlatkoB** [comment]
I just think it would be a nice thing to have it all in one tool, which already does that properly.

**Comment by gyunaev** [comment]
Unfortunately global key binding (meaning the key is active even if the application is in background) is something which is system-dependent, and cannot be reliably implemented in Birdtray. I will provide show/hide options, and then you can bind them to keys using your OS-specific tool (such as Settings in KDE).

**Comment by vlatkoB** [comment]
That's exactly what I meant. Thanks for looking at it.

**Comment by 6ber6** [comment]
I would be please (as it is the case with the extension minimizetotray that thunderbird minimizes also when we close it using the top right cross button, not only the minimize button. Because, currently, maany times I am using the cross button and thus birdtray as to start again Thunderbird. If somrone want to close definitively Thunderbird, he can either use the menu File->Exit or to configure birdtray to close Thunderbird when it exits. Thanks

**Comment by gyunaev** [comment]
@6ber6 this is not possible.
