### ISSUE TITLE
High CPU Usage every few seconds

### ISSUE THREAD

**Issue by jmdaemon** [gyunaev/birdtray#494]
**OS** Arch Linux 5.15.6-arch2-1:
**DE** i3-wm: 
**Birdtray Version** Birdtray version 1.9.0 compiled at Apr 25 2021 21:37:21 using Qt 5.15.2.
**Thunderbird Version**  Thunderbird 91.3.2
**Birdtray Origin** Build from source via AUR
**Qt Version** 5.15.2

**Description**
1. Open up htop
2. Monitor for highest cpu %
3. See birdtray at 100% CPU

**Expected behavior**
I expected birdtray to use maybe < 10% of the CPU or otherwise at the least some other minimal amount of CPU %. I don't quite understand the reason for why it ocasionally spikes to 100%, even though thunderbird itself is not even really doing anything, and even has a lower CPU usage than birdtray.

**To Reproduce**

1. Open up htop or use any other process monitoring tool
2. Monitor for cpu usage

**Screenshots**
![2021-12-04_10-10-cropped](https://user-images.githubusercontent.com/42862873/144720427-24060ee4-d814-47e4-b4c5-16afaf00cebd.png)

**Comment by MarekMalevic** [comment]
I had the same issue. And when I profiled birdtray I have found out it is caused by regular checking of the mails. I have 3 huge accounts and was checking them each few seconds. The parsing of the file is quite CPU resource consuming.

Since disabling the option "Force index file re-read" in birdtray setting and restarting of the app my CPU is ok. So maybe that is your issue as well.

So, this may probably be somehow improved on the birdtray but for me disabling the option just works.

**Comment by Abestanis** [comment]
@MarekMalevic is correct. Disable the `Force index file re-read` and the CPU usage will go down. You only need the setting enabled if you see that Birdtray is not updating the unread counter when you read a mail, or if it is too slow in updating it. Otherwise, disable it, because parsing the mail account data files every so often is CPU intensive, especially if you have a large mail account with many emails.

If you disable the setting and still see a high CPU usage, please reopen this issue.
