### ISSUE TITLE
Tray icon always shows 13 unread, no matter what

### ISSUE THREAD

**Issue by sonofevil** [gyunaev/birdtray#496]
**OS**: EndeavourOS/Arch, Linux-LTS 5.4.167, 64bit
**Linux Desktop Manager**: KDE Plasma
**Birdtray version**: 1.9.0
**Thunderbird version**: 91.3.2 64bit
**Birdtray origin**: birdtray package from AUR
**Qt version**: qt5-base 5.15.2+kde+r260-1 & qt6-base 6.2.2-1, 

**Description**
The tray icon always shows the number 13, no matter how many unread emails I actually have. If I select "ignore unread emails" the number goes away, but comes back on the next start.

**Expected behavior**
The tray icon shows the correct number of unread emails.

**To Reproduce**
Start birdtray.

**Additional context**
Birdtray automatically compiled using yay AUR helper.

**Comment by riidom** [comment]
This happened for me too, but it was because I apparently had two profiles in ~/.thunderbird, one old and unused, containing a few emails I dont use anymore, where some unread emails stacked up. Which, in return, got counted by BirdTray.

So maybe check first what profiles and emails you actually import. If there is no apparent gotcha, like in my case, then you maybe want to add emails one by one and check at what point the counter goes off-track.

I'm a new user myself, but maybe this helps for now :)

**Comment by sonofevil** [comment]
Yeah, there were some old unused profiles in there. I moved them to a different directory. After restarting Birdtray, the 13 was gone, but now it shows an orange exclamation mark, and if I hover over the icon it shows me a long list of errors of the form "Local Folders [xyz]: unable to watch xyz.msf for changes."

**Comment by Abestanis** [comment]
Birdtray is still configured to watch for changes in the folders that you moved. You can go to the `Monitoring` tab in the Birdtray settings and remove them there:
![Monitoring tab in the settings, the remove button is on the right](https://user-images.githubusercontent.com/6966049/148642328-b59733a1-24bc-4b1e-a338-aeae157802f1.png)
The ones which caused the warning should be highlighted.

While you are there, it might be worth checking if the folders configured there are the ones where you want Birdtray to look for unread messages or not.

**Comment by sonofevil** [comment]
Ah yes, thank you. That did it.
