### ISSUE TITLE
Custom icons not saved to .json

### ISSUE THREAD

**Issue by pmastrosimone** [gyunaev/birdtray#510]
**OS**: Windows 11 Enterprise(Education) 64-bit
**Birdtray version**: 1.9.0
**Thunderbird version**: 91.11.0
**Birdtray origin**: Installer from GitHub
**Qt version**: _NA_

**Description**
On Windows 11, a custom icon (.png format) is not saved properly to the json. When BirdTray exits it forgets both (if I'm lucky its only one). Looking at the .json produces a bunch of garbled text, not sure if this means that the PixMap is being exported to the .json (nor am I sure if that's correct behavior), but the path to the icon would probably be more reliable if so. 

Here's the two json variables:

```
   "common/notificationicon": "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAABjWlDQ1BHSU1QIGJ1aWx0LWluIHNSR0IAACiRfZE9SMNQFIVPU2tFKiJ2EHXIUJ0siIo4ShWLYKG0FVp1MHnpj9CkIUlxcRRcCw7+LFYdXJx1dXAVBMEfEEcnJ0UXKfG+pNAixguP93HePYf37gOEepmpZsc4oGqWkYrHxGxuRQy+IoAh9MGHTomZeiK9kIFnfd1TH9VdlGd59/1ZPUreZIBPJJ5lumERrxNPb1o6533iMCtJCvE58ZhBFyR+5Lrs8hvnosMCzwwbmdQccZhYLLax3MasZKjEU8QRRdUoX8i6rHDe4qyWq6x5T/7CUF5bTnOd1jDiWEQCSYiQUcUGyrAQpV0jxUSKzmMe/kHHnySXTK4NMHLMowIVkuMH/4PfszULkxNuUigGBF5s+2MECO4CjZptfx/bduME8D8DV1rLX6kDM5+k11pa5Ajo3QYurluavAdc7gADT7pkSI7kpyUUCsD7GX1TDui/BbpX3bk1z3H6AGRoVks3wMEhMFqk7DWPd3e1z+3fnub8fgAbpnKE61EPzgAAAAlwSFlzAAAOxAAADsQBlSsOGwAAE6ZJREFUeJztnXt8HNV1x39nZiX5gc3DYFmalySjojSiTfNxU0iKbSnmZZxA/DEGAonzoYTQhLQkJIXyaUIenwBNaUg+gaSmeUBq6kAoj5jYIdgWdktCWieNE5cEZLGauTOWbMfBD2y00u49/WMlY1tz766s3dXKnu9feOY39x50z87j3nPPARISEhISEhISEhISEhISEhISEhISEhISEhISEhISEhJONKhUDW3btu2U008/3ZZSzpTSqClVuwlvYhhyyDCM/a+99lrY3t7+einaPG4H2LlzZ30mk1nKbHQS4TwA1njaSxgTDCBi5hdNkzbU1NQ8WV9fv/N4GhrzgEVR9C4p+XZmXAIgdTydJpScLDN+DNDXPM9aP5YLi3aAKIrasln5DSLqGLt9CZWCCBsBvsVxnN8UozcKCZiZfD/8+1yOtyaDX/0wo5OZtgRB8BlmLji+2jvArl27ThkYyDwG0KWlMzGhUhBhbV1d7VWzZ89WvjAqHUAIccbwc+XPi+xvL4CXmbEHwMEx2ppQHNOJMAvAOQBOK+YCZv6FYeAix3H+EHc+1gG2bt06/fTTZ60HcF6B9nsAfJeIf2jb9jYi4mKMShgfzExhGLbncnS5YeBDAObq9fhZKkWLLMs6dOy5WAcIgvAxAFdqmuwnMj9t2w2riSg3JusTSgozm0EQXmMYdBczHLUOP/A8e/mxx0e9JPT2Bh+FdvBpdSYzcI7jNK5KBn/iIaKc5zmrBgbeaAfwfbUOVwZBeNOo40f+QwhhMRsvATxT0dkXHMe6c9xWJ5QN3xefI6LYMWLGASLZ5rrujpFjR90BpKR7VIMP4K5k8Ksfz3M+B+DuuHNEmAEYdx11bOQ/hBBnA8ZvmXnU7B4z1rqutSR5yZscMDMFQbSGCJcde44IWWbZ5rpuD3DEHUBK3Bw/+LxPyqG/SgZ/8kBEzJz9MIB9x55jRgowPjbybyN/kFMAXaNo757m5ub+8piaUC6ampr6mPGPitPv7+rqSgHDDiCEeCcRZscIXx8cHPhGuYxMKC+Dg1MfABA3C1jf0vJH5wHDDkBkqub4n2htbd2v62T79u2zfT98OAhCEQTi577vLxqX1QlKfD9aFAThz/N/6/Chvr6+s3T61tZZ+5n5qfizshN48xHw9ngRrdN10N3dXVdbO2UDET4IwAboHUTmuiCIri74f5MwJoIgupqI1wF4BwAbwIqhodyG7u7uOt11RMba+ON4O3D4DoBz4kS1tebPdY3X1dUtBdB+zOEUwKt8P1yhuzaheHxfXEeEf8Po+Itza2unXq67ljkbO4ZEdA5w+A6AOaMv5KH6+npf3zipbkEmEb4jxI4bdNcnFEaIHTcQ0cNxX2h5uF53veu6vcw8NOqq4TEfvgPQKccKiGg/EUld44aBtQAGVKcBXhkEwUd1bSSoyf/teCXUcRsDRBx7ix+BiCQRxb3HzQAAg5lTzGyOPs+DhQx0HGc7Mz4Q52EAkA9IMO4PgvCThdpKOBrfD28BjPs1QR1ZZqwYmdApQCbmmMnMqYIRI4XwPPtxIl6u6ATIzzbe6/vitvH2dbIQBOGtRPgK1PEag0R8tefZj423r3E7AAC4rvsUkbkUwBsKCRHRPb4vPl+K/k5kgiC8A8C9UA/+gGnSMsdx/qMU/ZXEAQDAcRrWmiZdDmBU0MEIRPTZ3t7gS6Xq80Rj+Aei+fvwgJS81LKsNaXqs2QOAACWZT1HxJcRkTIGzTCMO4IgvLeU/Z4ICBHdQ0Sf1UgOMdOSpiZHOzczVkrqAADgOM7zUmYvYWbdDOKtQkRfZ+ZkIwmAIAjvY2blOxIRHQDkpZ5nbyh13yV3AADwPO8FKeliAK+pNMx8sxDRN09mJxhetr0fwC0a1T4ps5e6rru5HDaUxQEAoLnZfpHZuBBAbDTqMB8RIvxWMfHrJxr5wQ9XAvwxjWYvUeoiz/NeKJcdZf3De17jL7LZwU4Au9Uquj4Iwu/Fz0WcmDCzIUT0XSL6sEa2J5UyOh2n4b/LaUvZf3ktLS1bmc2FACtjCojoWiGi1erpzhOHrq6ulO9HjwBQrpUwYxcRd1iW9b/ltqcit17Pa3gplzM6AI40siuFCB/btm1bbSVsmgiYuaalpXW1YUC5WsrMfbW1Zkexe/vGS8Wevc3N1u+IsJAImgUmet+MGac9kU6np1TKrkrR3d1dJ0T0OBGWaWSRadLChoaGlyplV0VfvhzH2Z7NDi1k5ldVGiJcZpqpp4UQUytpWzlJp9NTpkyZ+gSA92pkAXNuvm3br1TKLqDCDgAAzc3NvamUsRDAdrWKLpKSftTf3z+9QmaVjS1bommmWbOGGYtVGmZOp1LGfM/zlD+McjEhn1+WZQlALiDC71QaInQMDubW7t69e0YlbSsl27btOqW+np8BoAyTI8IrhoELGhsbtbEX5WLCvr9d191RU5NaAPA2tYrnDwxknk2n00XthK0m9uzZM3PGjMEfM0OTU4FeymZrFziOo3s5LisTOgEzZ86cXZlMqpOIlJ87zDjfMFLP+b5/eiVtGw/pdPq0gwff+AkR3qWR/TqbzXQ2N8+e0JD7CZ+Ba21t2A3IRQD/j0pDRPMMI7UxiqIzK2nb8SCEOMM0azYA+AuVhhm/Mgx0trS0HFdip1Iy4Q4AAI7j/GFoaPBCAC+qNMz8tlxOPv/qqzu1MXATSV9f31nMeB6AIsoayDt6rtO27T2VsktHVTgAAMydO3ffoUOvXwTQf6pV9NZUaqgrCHY3Vs6y4ujt7W0YGsp2AXSuSkOEn2YyA4s8z1MuklWaqnEAAGhrazuwf/9ri5mxUSN7C5B5PgxDu2KGFSAIgkaiVBdAb1VpiLDp4MHXLym00abSVJUDAEB7e/vrhsFLAH5WI2uVkjb7vt9SMcMURFHkAMZm1d6KYdYbBi1ua2s7UDHDiqTqHAAAHMd5I5OxLyfCj9QqbiYyu4Ig0ObHKSe9vb3NuRxvhjZHDz+byw29Jy4/TzVQlQ4AAK2tlNm3b+9SInpSI3MB2vzqq5Hu11cWhBCthpHaDKBJI1vjOPZ7m5ubVXsnJpyqdQAAaG9vH9y+/ZXlAD2qVlFjKoVNfX19yudvqent3fEWZtqE/B69eKsIT+zfv3cZERXcXzGRVLUDAEBHR0fWcRqvZcYqtYrrs1m5MQzDPy23PUKIc4lkF4AGjez7tm1d1d7eXtWDD0wCBwDymbBc11oB4CGVhplnS4kNvb07NN/g4yOdTr+NmTYSQTkXwYxVjmNdR0TZctlRSiaFAwD5PW6OY10PYKVGNssw5AYhhHIW7ngJgh3zTDO1EYBmNpK+7brWismUPm/SOACQz30D0BMAdL+u06Sk53w/+stS9RuG4fmAXA+Qdj2CCGGhDbXVxqRygCiKLgf4aRSoU0CEGUS8LgzDcWc3D4JgvpT0YwCnFtIy851BEH5lvH1WkknjAL294tpcjn8AoNhwsVOkxDNBEF10vH2GYfhuwFiryZ0YxyeECFdOllD3SWGkEOJG0zQeBjDWWkTTAH66t1coo3FUBEFwsZRYA2DMUUnMuFGIHau2bNlS9bWTqt4BwjC8hZn+RbNvgJl1M4aYQoQngyC4otg+fT96D2A8DUAZl0iEBwHWLOrwNWedVV/1Aa5V7QBBEH5GStwH9VbpHJFxo+fZSwDcinwxpVEQUS1gPOr7oSYJdh4hdrwPkI8DUCVfYiK6zXHsj2SzQx1EtEvVFhEtMc2aNdUc21i1DhAE4p8AfEEjGZKSVzhO47cAwHXtrwDy41A4AYBaIvy7EOJadZ/RVczy0bzDxMLM/AnHsb4M5De9ZLNYACDU2Lkok8k+l06/VpVhbVXnAPltU+FKgD6lkQ0AtKypyXnkyIOu6z5AZNwEQPUplmKmh+MymA1n4loF9XuGBOhmz3O+duTB5mbrd6ZJ7ywQ6n6+aR7c0N3drc3rNxFUlQN0dXWlwjB6mBk3amQHDQNLXNf6YdxJx2l8EKAbNJMxJhG+4/vicB9BEF2vz8QFycw3ua4VmzXVsixBxBcA/H8au99eVzd1kxDC0mgqDjFzSogoJskT97muU7HIm+7u7rq6uimPAqTLe7eXmZZ4nlVwt2xvr7jWNOmhfHLkWJiZ/5aIskSkS8aUY8b1nmd/r1CfYRjOkhI/gTYkjNLM2UWV3AMQBGEEYNRYOo5VUxV3gCiKptXVTXu6wOD/XkrqLGbwAaCpyXmECNeoMpghn7foawAe0GXiAuR1xQw+ANi2vWdoKNMJ4L/UKm4mMjf7ft8fF9NmuZlwB+jp6Tk1l+NnAb5YI4uYzQVNTWPbLWvb9uNERqEMZspMXMy4xnVdZRmWOObOnbvPNOligHQRTRaQ6wrD8G1jabscTKgDhGE4q6am7jkAynl7ZvQy5+Z73vFtmHRd6ylmuhLqhJZxDDDTMs+zHz+ePi3LOpTJHBqZto6FCLOlRFcURe88nj5KxYQ5QBAEjVLyJgCauoT028FBXDDe56XnWWsA4wqo09gdyRuAcUX+muOntbU109OzfRkzP6KRnZbL8U98P3z3ePoaDxPiACOBlPooWvpVJmMsaG21dd/YReO6jc8aBpZAX9Ry+AujUXf7LpqOjo6s69ofZKZ/1cimE+GZIAh0O4fLRsUdIJ1Ot0nJL0ATSEmEn0mZ7czvGiodtm1vBORixOcyPATIxXlN6SAi6XnWjQD+WSObAhiPT0Sa/Yo6gBDiT0yztktX4BDA+pqa1IXl2jzhuu5mInMxM44I0ab9RLy4XJm48v3an2JmXabUGoBXCSEqmmG9Yg6QTofnMVMXwKNS049AhGdyuaH3zJkzp6y1hx2nYZNpollK/jhANxsGtziOs6mcfQKHS7p9EurpapOZHqxkcu2KJGUSQixkxhoAo9LSvwmt3rmzb8W8efNU3+0lZXhv3v2V6OtIXNe+z/fDQ4ZBDyhWOAnAvUJEpziOpVsLKQllvwMI0beYmdZCP/jfefHFFz5QqcGfaDzPXsmcU6bZR36G9vPDC2JlpawOEIbhMubck9CsqwP4quM03rB8+fJJE0hZClzXXU1kLGdm1SQVAPpUEITfvPPOO8s2TmVrOAjCDzHTagC6tG9fcl37EydrUUrXtZ4CjCW65NoAbrr++hseLlcizbI4gBDib4jo25rVNZaS/8517X8oR/+TCc+z1hsGLkZMlc8RiOi6MIweY+aS51AsuQP4vridmb6qWWCRAN3c1OSU/fk2WbAs66fMuXcTkXLegxlLhdixJoqiaaXsu6QO4PvR3UR0N9QLLFkiY4VqXf1kxvO8X5gmLWDmPrWKL5IS67q7u8cSpaylJA7AzCRE9HUivl2jGSTiqx2nUbPH7+SmsbHxt0R8gS66iJnn19VN2/Dyy6XJl2QMB0TEvIEr4+KONcgUInqImW9WaYhwkIjfW6o6Nycyruv2GAbmM+NltYrnTZ3KG9PptHJS7RjiAlxzRJQdKR076i2UmWcWs7lBiOjLAD6oVtB+Znmp67olWWA5GXAcJ8rlBhcw41ca2bmGUbN2pAq4iuExjHtkHADerBw6KlcdEdUEQdBUoHETwF+rzhPh90Bukeu6msRPCXG0tLTslHKoA2Bl+V4i/NnZZ5+ty0WIINjZhJhA15ExH6kdHHu7IUq9owhbY7/hmblPSnOh67rK/H8Jepqbm/ceOnTwQgDPqzTMrJ1DMYyh8+KOE/HLwJvVw3+pEGm3VBFRjpm/FXOq1zAw3/MadFGyCUXQ1tZ2gIgXM2NUiVgi/NpxnAIxknRp3FFm/BI4fAfg2DVwZizt7t6j/eQ4cGDfpwF8gzlfapYZXZkMLnAcR5MNPGEsOI7zhutaVwD8AIAhAEyEDZkMLdHlItizZ89MgGK3xKVSxgZg+Hs9Hxq+I4yrRM2MOzzPvruQkVEUTZNSTnEcR1ckKmGc9Pf3T89kMrXFxEsMVyGNKURJ/T09rzgdHR1ZOkJ8H2LLl9F+KYfampqaNBMUCdVGEASNgPESYvIaSCnva2pyPwkcNREk70ds5g2eaRipb5/M9f0mG8xMzMaDiE9qkSXiw3EQhx3Add0eIqxWtHlpEIR3ldjOhDIRhjvuJsJlitOrjoyyPmqih1nerir5SkS3B0FY9giVhPHh++Lz6jK0tF/K7B1HHTlWEgThTQC+qenj0enTp944a9asqkp6fLLT09Nzak1N3YMAlqs0zLjJ8+yjsqzFPteDIHxU1xBA/cx8m+taj0ymlGgnIsxsRlH0filxFzSZSwE85rr2VccejHWA/Ccdr2fG+QW6fxWgh4j4adu2f3OyRvZUGmamMNx1LvPQ5QA+BECbNZ0ZP929my6cN290wmrlm70Q4gyA1jGjmOlgMPM+IrzMTL+HfvdNwvEznQhnMvM5RFQwbV0e2kIkL1bNz2g/7bZu3Tr9jDPO/D4zLxm7rQkTDRGe2bdv7zXt7e3KmMOC3/bDZc4/TYQvFhsjkDCxMPOgaZqfs6yGewo9loue3EmnozbTxNcBVhZBTKgG6DkieWuxxafHPLvn+9G7AL6NCJdg7IkbE8rDEEDrDIO/att211guPO7p3f7+/tmZTPZ9ROgkwnkA2ZMlPepkh4gkM4cAXmTGxrq61JNz5sxR5ivUtlUqo7Zu3Tp9xowz7VTKmMksk3eFMkBkDGazcn9dHUS11iBKSEhISEhISEhISEhISEhISEhISEhISEhISEhISEhImHj+H3HhChZX6WY7AAAAAElFTkSuQmCC",
   "common/notificationiconunread": "",
```

**Expected behavior**
Icons to be saved properly and appear on next program start.

**To Reproduce**
1. Set icon (in this case, .png format) for both unread and read.
2. Exit program or reboot computer
3. Reexecute Birdtray, where one or both icons will be missing
  
**Edit:** Here are the source .png files I'm using, 

![mail-yellow](https://user-images.githubusercontent.com/66535355/181667775-9c2d664f-4157-4f34-9d2f-18a807fdd2ec.png)
![mail-simple-dark](https://user-images.githubusercontent.com/66535355/181667777-68ca97b7-1520-435e-9731-1a757c509538.png)

**Comment by Abestanis** [comment]
Hey, thank you for the detailed description and providing the two images, this will make it much easier to find out what's the problem.

I just tried it with both icons on a Windows 10 machine, and both icons were saved correctly. Could you please describe step 1 into more detail, e.g in which order do you set them and did you check the `Different icon when unread` checkbook?

Also, if you have the time, could you try the following:
* Try with different images and see if the same problem happens.
* Stop Birdtray and move the configuration file somewhere else. This will cause all settings to be reset to the default. Now start Birdtray again and try setting the icons. After the test you can just stop Birdtray again, delete the new config file and move your old one back, that will restore your settings.
* When changing the icons, are there any error or warning log messages? You can see them in the `Advanced` tab by clicking on the `Show log window` button.

> Looking at the .json produces a bunch of garbled text, not sure if this means that the PixMap is being exported to the .json (nor am I sure if that's correct behavior), but the path to the icon would probably be more reliable if so.

We are indeed storing the PixMap into the Json file. We choose this instead of a path to make the Birdtray installation more movable between computers, but more importantly so that we can keep showing the icons even when the original file is removed or moved.

**Comment by pmastrosimone** [comment]
```
2022-07-29 11:27:34 Birdtray version 1.9.0 started 
2022-07-29 11:27:34 Triggering the unread counter update 
2022-07-29 11:27:34 Unread counter for C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/d51z9i76.default-release/ImapMail/xxx/INBOX.msf: 0 
2022-07-29 11:27:34 Unread counter for C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/d51z9i76.default-release/ImapMail/xxx/INBOX.msf: 0 
2022-07-29 11:27:34 Unread counter for C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/d51z9i76.default-release/ImapMail/xxx/INBOX.msf: 0 
2022-07-29 11:27:35 Unread counter for C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/d51z9i76.default-release/webaccountMail/xxx/Inbox.msf: 22 
2022-07-29 11:27:35 unreadCounterUpdate 22 
2022-07-29 11:28:02 Triggering the unread counter update 
2022-07-29 11:28:02 Unread counter for C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/d51z9i76.default-release/ImapMail/xxx/INBOX.msf: 0 
2022-07-29 11:28:02 Unread counter for C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/d51z9i76.default-release/ImapMail/xxx/INBOX.msf: 0 
2022-07-29 11:28:02 Unread counter for C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/d51z9i76.default-release/ImapMail/xxx/INBOX.msf: 0 
2022-07-29 11:28:02 Unread counter for C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/d51z9i76.default-release/webaccountMail/xxx/Inbox.msf: 22 
```

There's the log afterwards (certain things redacted for privacy), removing the .json did not fix, still had suffered the same issue. It seems that using different icons *does* work, but it may take some more testing before I can say for sure. In prior testing, the images were originally in my home folder, but I had moved them (to the Program Files/Birdtray folder) to see if it would help, now moving them back seems to have fixed it *for now*, though again in the past I still had the issue. I will keep the issue open for a few more days just to confirm that this was indeed the issue. Thank you for your help!

**Comment by Abestanis** [comment]
I'm now also on Windows 11 and I still can't reproduce this.

> are there certain restrictions when working with .pngs or cases where it won't like what it's given?

Yes, we already had some images that Qt didn't like (see #356 and #392). In those issues, Qt was able to load the image, but couldn't save it into the settings. That is why we added a check when you select a new image, which verifies that saving the image will work and not just produce an empty string (`""`). In that case we will display a dialog claiming that the icon is invalid.

This is why I'm confused by your issue. The images you use are valid, I'm able to save them, and so are you... except not always, it seams. The fact that you see `"common/notificationiconunread": "",` in your config means that when you loaded the icon and we tested if we could save it, we could, but later when you hit `Ok`, we are unable to save it.

I'm really not sure what could cause this, from your description in point 3 it sounds like whatever is happening screws up saving for all images somehow. If we want to resolve this we need to find a way to replicate it consistently and then make small changes so we can identify the cause. Maybe your computer is running low on memory? You could check that via the Taskmanager.

Please let me know if you still have this problem, or if it fixed itself at some point maybe with a Windows update.
Also, regarding your point 4, if you don't click `Ok` in the settings dialog, ignore a new version of Birdtray or click `Don't ask again` in the dialog that pops up after launching Birdtray with no accounts configured, Birdtray will not attempt to save the settings, so you don't have to mark the config file as read-only.

**Comment by pmastrosimone** [comment]
I still have the issue, but I did find out some more things in my testing. I *think* it has something to do with the edition of Windows (e.g., Enterprise). I thought it may be due to HVCI on my machine, so I used the "Windows Sandbox" utility (which does not use HVCI) to test that theory, but I still had the same issue, leading me to believe it may be edition-bound somehow. I can't say 100% what it is or why unfortunately. It certainly isn't a memory issue (32G of RAM and I don't think I've ever gone above 16G). Ditto to the inconsistency making this much harder to diagnose/fix. If I have time (and the ability to) build from source and possibly hook a debugger into it I will give it a go.

**Comment by Abestanis** [comment]
> I think it has something to do with the edition of Windows (e.g., Enterprise).

I will try to set up a virtual machine with Windows Enterprise, maybe I can replicate it there.

> I thought it may be due to HVCI on my machine, [...]

Good idea, I don't have HVCI enabled because it interferes with my virtual machine software, so I'm glad you were able to test it and rule it out.

> It certainly isn't a memory issue (32G of RAM and I don't think I've ever gone above 16G)

Yeah, definitely not a memory issue.

> If I have time (and the ability to) build from source and possibly hook a debugger into it I will give it a go.

That would be awesome. I have a version of Birdtray with some additional logging for the pixmap saving, which might help us track down the issue. Download the source code from [the `test/pixmap_save` branch from my fork](https://github.com/abestanis/birdtray/tree/test/pixmap_save) instead of this repository, it includes the logging. I have also built an installer with these changes, you can download it [here](https://github.com/Abestanis/birdtray/suites/9347592405/artifacts/439746068).

If you can get a debugger to work, even better. The interesting function to look for is `Utils::pixmapToString` in `src/utils.cpp`, which itself uses `QPixmap::save`. The source code for that can be found [here](https://github.com/qt/qtbase/blob/0d20e6e4957b3842b659522f330b8a201ef8e505/src/gui/image/qpixmap.cpp#L822-L839).

Regarding building on Windows, yeah, sorry about that, we don't really have documentation for building on Windows yet. It's a bit of a hassle to get everything in the right place.
You can get inspiration from our [CI script](https://github.com/gyunaev/birdtray/blob/master/.github/workflows/main.yml), but you'll basically need:
* A C++ compiler. If you want to use the same compiler that was used to generate the Birdtray from the installer, download Visual Studio Community edition from [here](https://visualstudio.microsoft.com/downloads) and when prompted, select the `Desktop development with C++` package during installation. Then, on the right side, make sure to deselect `MSVC v143 - VS 2022 ...` and instead select `MSVC v141 - VS 2017 ...` further down in the list. Also make sure that the `C++-CMake-Tools for Windows` are selected.
* Qt 5.14.1 follow the steps [here](https://doc.qt.io/qt-6/get-and-install-qt.html) and download it via the installer. If you have installed Visual Studio, make sure to select `MSVC 2017 64-bit`. After installation, set the `CMAKE_PREFIX_PATH` environment variable to the path where Qt is installed. For example, my  `CMAKE_PREFIX_PATH` looks like this: `CMAKE_PREFIX_PATH=D:\ProgramData\qt5\5.14.1\msvc2017_64\`
* Cmake from [here](https://cmake.org/download) (latest release, Windows x64 Installer or Zip), although I'm not sure if this isn't already installed with Visual Studio. Visual Studio has a Developer Command Prompt, if you open that and type `cmake` and you get a usage, you can skip this.

With this, you should be able to open the sources in visual studio as a cmake project and build/debug from there.
Let me know if you encounter any problems.

**Comment by Abestanis** [comment]
Good news! I was able to replicate the issue in a virtual machine with Windows Enterprise. Looks like your feeling was correct.
I'll report back when I find out more.

**Comment by Abestanis** [comment]
Actually, with the installer that was created by the CI, I'm able to replicate the issue on a Windows Home as well.
I'm developing locally with MSVC 2019 and Qt 5.15.2, so I changed the CI to also use these versions and that fixed the problem for me. 
Please try [this version](https://github.com/gyunaev/birdtray/files/10027120/installer-Windows-x64-24ed3cb8ecdc3c29e08bd026398361cd2e21204b.zip) and see if it fixes the problem on your machine as well.

**Comment by pmastrosimone** [comment]
Beautiful, issue fixed and closed. Thanks for your help!

**Comment by Abestanis** [comment]
Awesome, thanks for your feedback and help tracking this down!
