### ISSUE TITLE
not working in my Cinnamon 19 based on Ubuntu 18.04

### ISSUE THREAD

**Issue by phd21** [gyunaev/birdtray#77]
Hi Birdtray developers,

Thank you for providing this application.

But, I just installed this into Linux Mint 19 Cinnamon based on Ubuntu 18.04 bionic and it does not work. Originally it came up and asked to set itself up, so I followed the instructions to use my default TB folder, but it never showed in the system tray nor can I adjust its settings because there is no icon. I rebooted, purged it, reinstalled, still no go. I did not have Thunderbird running when I first ran Birdtray, should I have?

I could not find a configuration file for birdtray or some way to reset it, so that I could get back to the original settings screen, not even from the console copmmand? How can we reset this birdtray app to its original installed state or to force a setup window to appear?

I even compiled it from source and I still cannot get birdtray to work? It seems like Birdtray is remembering the original installation configuration even after I purged it or I would get the original setup screen, right? What file(s) can we delete or change to get Birdtray to show its original setup screen?

Here is what console terminal shows.

birdtray:14623): Gtk-WARNING **: 11:32:02.687: Failed to parse /home/user69/.config/gtk-3.0/settings.ini: Permission denied
Triggering the unread counter update
Window ID found: 0
UnreadCounter generated an error: Folder  was not found in database

Thanks,
Phil (phd21)

**Comment by Abestanis** [comment]
Hi Phil, thank you for using Birdtray.

As a disclaimer right away, I'm not an official Birdtray maintainer, but I might be able to help you anyway.

> I did not have Thunderbird running when I first ran Birdtray, should I have?

No, that is not necessary.

> What file(s) can we delete or change to get Birdtray to show its original setup screen?

The settings are saved in  `~/.config/ulduzsoft/birdtray.conf`. You should be able to delete the file to reset the settings. But before you do that, could you please
a) post the contents of the file here and
b) download, compile and run Birdtray from [this branch](https://github.com/Abestanis/birdtray/tree/fix/emptyAccountURIs). This should detect the invalid account settings and remove them for you. Assuming that you didn't add another valid account in Birdtray, this should prompt you to set up your accounts again.

> How can we reset this birdtray app to its original installed state or to force a setup window to appear?

You are right, we should think about adding some command line options. @gyunaev What do you think of a `--reset-settings` to reset the settings and `--settings` to force showing them after start?

> ... [Birdtray] never showed in the system tray nor can I adjust its settings because there is no icon.

This one is going to be tricky, because I am not able to verify that in a virtual machine with the latest version of Linux Mint (19.1, Cinnamon, 64bit) which I downloaded [here](https://linuxmint.com/edition.php?id=261). The icon shows up even with the invalid account in the config. Could you please tell us the exact version of your Linux Mint, if you are using the default windowmanager and desktop or if you installed any other application that modifies the system tray in any way. Also, if you are using an outdated version of Linux Mint or any software on your computer, please try to update them, if that is possible.
